import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins as PoppinsFont } from "next/font/google"; // Corrigi aqui
import "./globals.css";

// Agora a variável se chama poppins, com letra minúscula
const poppins = PoppinsFont({
  weight: ["300", "400", "600"],
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
